### ISSUE TITLE
Camera intrinsic parameters

### ISSUE THREAD

**Issue by nas-git-nas** [goyoambrosio/RobotAtHome2#2]
Thanks a lot for the well-structured dataset!

I was wondering if there is any way to get the camera's intrinsic parameters. In particular, I am looking for the focal length.

Thank you.

**Comment by goyoambrosio** [comment]
Hi! The camera model is [Asus XTion Pro Live RGB-D camera](http://xtionprolive.com/asus-xtion-pro-live). You will find the calibration parameters [here.](https://mapir.isa.uma.es/mapirwebsite/?p=2318#Calibration_parameters). Hope this info is useful for you.

**Comment by nas-git-nas** [comment]
Thank you very much for the quick response. That was very helpful!

**Comment by goyoambrosio** [comment]
You're welcome !
